### ISSUE TITLE
Crash randomly occurs when applying your mixins

### ISSUE THREAD

**Issue by AlyceOsbourne** [Harvest-Festival/Simply-Seasons#4]
Hey, your mixin has a rogue assert it seems. 

`[pool-3-thread-1/WARN] [mixin/]: Mixin apply failed simplyseasons.mixins.json:SSWorld -> net.minecraft.world.World: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @At("INVOKE") on net/minecraft/world/World::getTemperature with priority 999 cannot inject into net/minecraft/world/World::func_175727_C(Lnet/minecraft/util/math/BlockPos;)Z merged by sereneseasons.mixin.MixinWorld with priority 1000 [ -> redirect$zzl000$getTemperature(Lnet/minecraft/world/biome/Biome;Lnet/minecraft/util/math/BlockPos;)F -> Prepare]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/world/World::getTemperature with priority 999 cannot inject into net/minecraft/world/World::func_175727_C(Lnet/minecraft/util/math/BlockPos;)Z merged by sereneseasons.mixin.MixinWorld with priority 1000 [ -> redirect$zzl000$getTemperature(Lnet/minecraft/world/biome/Biome;Lnet/minecraft/util/math/BlockPos;)F -> Prepare]
	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:293) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:375) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1255) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1033) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569) [mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) [mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:223) [mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformationHandler.processClass(MixinTransformationHandler.java:121) [mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.launch.MixinLaunchPlugin.processClass(MixinLaunchPlugin.java:131) [mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:154) [modlauncher-8.0.9.jar:8.0.9+86+master.3cf110c]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) [modlauncher-8.0.9.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:879) [?:1.8.0_292]
	at net.minecraft.block.Blocks.<clinit>(Blocks.java:30) [?:?]
	at net.minecraft.world.gen.surfacebuilders.SurfaceBuilder.<clinit>(SurfaceBuilder.java:12) [?:?]
	at net.minecraft.world.gen.surfacebuilders.ConfiguredSurfaceBuilders.<clinit>(SourceFile:11) [?:?]
	at net.minecraft.util.registry.WorldGenRegistries.func_243674_g(WorldGenRegistries.java:33) [?:?]
	at net.minecraft.util.registry.WorldGenRegistries$$Lambda$642/0x0000000000000000.get(Unknown Source) [?:?]
	at net.minecraft.util.registry.WorldGenRegistries.func_243668_a(WorldGenRegistries.java:89) [?:?]
	at net.minecraft.util.registry.WorldGenRegistries$$Lambda$650/0x0000000000000000.accept(Unknown Source) [?:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684) [?:1.8.0_292]
	at net.minecraft.util.registry.WorldGenRegistries.<clinit>(WorldGenRegistries.java:88) [?:?]
	at net.minecraft.util.registry.Registry.<clinit>(Registry.java:464) [?:?]
	at net.minecraft.util.registry.Bootstrap.func_151354_b(Bootstrap.java:38) [?:?]
	at net.minecraft.client.main.Main.lambda$main$0(Main.java:123) [?:?]
	at net.minecraft.client.main.Main$$Lambda$588/0x0000000000000000.run(Unknown Source) [?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_292]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
	at java.lang.Thread.run(Thread.java:823) [?:1.8.0_292]`

Just needs to be swapped wit a != null check I think

**Comment by joshiejack** [comment]
What version
